#! /usr/bin/bash
#
# retrieve sound file(s) with specified title and artist name
# Possible to package into album forman with given specifications
#
#
#








verbose='false'
hflag=''
Aflag=''


while getopts 'A:h' flag; do
    case "${flag}" in
	h)
	    if [ "$#" != "1" ]
	    then
		echo " albumify -h takes no non-option commands"
		exit 0
	    fi
	       hflag='true'
	    echo "Overview: Enter a media source and artist name and get corresponding sound media file(s)"
	    echo " "
	    echo "Usage:"
	    echo "$ albumify [FLAGS] 'Media Source Name' 'Artist Name' "
	    echo " "
	    echo "FLAGS:"
	    echo "-h                     displays this segment for brief help"
	    echo "-A                     will get Album with title 'Media Source Name' by 'Artist Name'"
	    exit 0
	    ;;
	A) Aflag='true'
	   ;;
	v) verbose='true'
	   ;;
	\?) echo "Please enter albumify -h for help on commands"
	    exit 0
	    ;;
    esac
done






album=''
song=''
artist=''

#
# need to check for the number of arguments
# need to check for if the media / artist could be found
#

#if you indcate an album 
if [ "$Aflag" == "true" ]
then

    album="$2"
    artist="$3"
    FILE=$4

    
    sleep 1
    echo "Getting tracks from $album by $artist..."

    mkdir "$album"
    
    while read line
    do
	song="$line"
	./search.py "$song" "$artist"
	mv *.m4a "$song.m4a"
	mv "$song.m4a" "$album/"
	((k++))
    done < $FILE
    

    
else
    song="$1"
    artist="$2"
    ./search.py "$song" "$artist"
    mv *.m4a "$song.m4a"

fi






